using System;
using System.IO;
using System.Text;
using System.Xml;
using Godot;
using GodotTools.Internals;

namespace GodotTools.ProjectEditor
{
    internal static class LocalDevelopment
    {
        private const string PropsFileName = "Godot.LocalDevelopment.props";

        private static string SourcePropsPath =>
            Path.GetFullPath(Path.Combine(GodotSharpDirs.DataEditorToolsDir, "LocalDevelopment", PropsFileName));

        private static string ProjectPropsPath => Path.Combine(
            Path.GetDirectoryName(GodotSharpDirs.ProjectCsProjPath)!,
            ".godot",
            "mono",
            "local_sdk.props");

        public static bool IsActive => File.Exists(SourcePropsPath);

        public static void Synchronize()
        {
            try
            {
                if (!IsActive)
                {
                    if (File.Exists(ProjectPropsPath))
                        File.Delete(ProjectPropsPath);
                    return;
                }

                string contents = CreateProjectProps(SourcePropsPath);
                if (File.Exists(ProjectPropsPath) && File.ReadAllText(ProjectPropsPath) == contents)
                    return;

                Directory.CreateDirectory(Path.GetDirectoryName(ProjectPropsPath)!);

                string temporaryPath = ProjectPropsPath + ".tmp";
                File.WriteAllText(temporaryPath, contents, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
                File.Move(temporaryPath, ProjectPropsPath, overwrite: true);
            }
            catch (Exception e)
            {
                GD.PushError($"Failed to synchronize local C# development settings: {e}");
            }
        }

        private static string CreateProjectProps(string sourcePropsPath)
        {
            var result = new StringBuilder();
            var settings = new XmlWriterSettings
            {
                Indent = true,
                NewLineChars = "\n",
                NewLineHandling = NewLineHandling.Replace,
                OmitXmlDeclaration = true,
            };

            using (var writer = XmlWriter.Create(result, settings))
            {
                writer.WriteComment("Generated by a local Godot .NET editor build.");
                writer.WriteStartElement("Project");
                writer.WriteStartElement("Import");
                writer.WriteAttributeString("Project", sourcePropsPath);
                writer.WriteEndElement();
                writer.WriteEndElement();
            }

            return result.Append('\n').ToString();
        }
    }
}
